name = "gardenlog-ai"
account_id = "049ff5e84ecf636b53b162cbb580aae6"
main = "src/worker.ts"
compatibility_date = "2024-01-01"

[vars]
# Set these via wrangler secret put
# DEEPSEEK_API_KEY

[[kv_namespaces]]
binding = "GARDEN_KV"
id = "7bbca24f87d2499c9348cd29b26bfa90"

[[kv_namespaces]]
binding = "KG"
id = "7bbca24f87d2499c9348cd29b26bfa90"
